version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: finance-postgres
    environment:
      POSTGRES_DB: PersonalFinanceDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finance-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=PersonalFinanceDb;Username=postgres;Password=postgres
    ports:
      - "5000:8080"
    depends_on:
      - postgres
    restart: unless-stopped


volumes:
  postgres_data: